### ISSUE TITLE
Add ability to specify question text when creating survey

### ISSUE THREAD

**Issue by dipshit** [vikrambombhi/SimpleSurvey#10]
We got the dropdowns for adding questions in #5 but lets set the question ~titles~ text as well.

**Comment by bkzhang** [comment]
Whats the difference between the questions and question titles, why do questions have a title?

**Comment by dipshit** [comment]
@bkzhang they are the same. On the frontend they are called titles from leftover code I wrote, and this is a frontend issue. A corresponding backend issue needs to be made as well I think (to modify the /new endpoint)

**Comment by bkzhang** [comment]
@dipshit can we closed this? I believe it was covered by #63
