### ISSUE TITLE
Get react tooling working

### ISSUE THREAD

**Issue by vikrambombhi** [vikrambombhi/SimpleSurvey#25]
## What needs to be done
React is the future so we need to use it. Step one is to get tooling for react working

**Comment by dipshit** [comment]
I think we should use vue.js as it has more stars on the repo.

https://github.com/vuejs/vue

https://github.com/facebook/react

**Comment by vikrambombhi** [comment]
React is a more mature library and is more popular according to this 

https://miro.medium.com/max/3006/0*wXOvxdrwp8FEXsGR
