### ISSUE TITLE
Generate graph response from question

### ISSUE THREAD

**Issue by dipshit** [vikrambombhi/SimpleSurvey#35]
When a survey is closed #34 all of the questions have their data compiled into a graph. The graph should be saved to disk, and the filename returned to the survey for displaying.

From the project doc: 
> survey result is generated, compiling the answers: for open-ended questions, the answers are just listed as-is, for number questions a histogram of the answers is generated, for choice questions a pie chart is generated

**Comment by dipshit** [comment]
https://github.com/knowm/XChart
https://mvnrepository.com/artifact/org.knowm.xchart/xchart

possible solution with a graph generator ^

**Comment by bkzhang** [comment]
How would we do this with a text question

**Comment by dipshit** [comment]
https://github.com/vikrambombhi/SimpleSurvey#simplesurvey

for open-ended questions, the answers are just listed as-is

**Comment by dipshit** [comment]
closed by #101
