### ISSUE TITLE
Weekly scrum - [3/6/2020]

### ISSUE THREAD

**Issue by bkzhang** [vikrambombhi/SimpleSurvey#7]
This week I've added the `.travis.yml` #2 and added functionality to support the tests #3 as well as added some tests to `Survey` and `TextQuestion` #4 

Next week I will add some additional controllers #6 

My local environment is holding me back a bit, intelliJ is not recognizing the TextQuestion model

**Comment by ismail-syed** [comment]
**This week:** 

* https://github.com/vikrambombhi/SimpleSurvey/pull/8
  * Added the `SurveryController` so we can expose the REST API to query the survery
  * Add some styling to the app 
  * Update the app to request survey data from the API

**Next week**
* Need to sync up with the team to find out what to pick up next

_No blocking issues for me_

**Comment by dipshit** [comment]
This week I added the first iteration of the SPA: https://github.com/vikrambombhi/SimpleSurvey/issues/9

Next week I will:
 * Review #8 
 * Work on creating questions for surveys at the frontend: https://github.com/vikrambombhi/SimpleSurvey/issues/10

**Comment by JackyChiu** [comment]
## This Week
- added tests for models with #15 and #16 
- reviewed PRs

## Next week
- help and missing functionality to the `SurveyController` such as closing a survey

**Comment by vikrambombhi** [comment]
## This week
- Created model for `TextQuestion`
- Created model for `RangeQuestion`
- Created model for `OptionQuestion`
- Got continuous deployments working for Heroku
- Fixed bug where the favicon was getting 404ed on prod

## Next week
- Controllers for creating a survey
