### ISSUE TITLE
Send questions properly when submitting new survey

### ISSUE THREAD

**Issue by dipshit** [vikrambombhi/SimpleSurvey#73]
need to choose a format to receive the JSON and deserialize it into a survey.

**Comment by dipshit** [comment]
Does anyone know the proper way to do this? I think the easiest way would be to make the signature for the `/new` POST function something like: 

```
public Survey newSurvey(@RequestBody Survey survey, @RequestBody List<OptionQuestion> optionQuestions, @RequestBody List<TextQuestion> textQuestions, @RequestBody List<RangeQuestion> rangeQuestions)
```

With react do we still have a `GET /new` create a new survey, and then have the client `POST /new` to save their changes to it? Or do we so something different like I just suggested ^.

Thoughts?

**Comment by bkzhang** [comment]
Here's the json format for the survey object in `/new`: https://github.com/vikrambombhi/SimpleSurvey/pull/33#issuecomment-601455723

Don't need to include things like id etc, its just what the object mapper outputted during the test

**Comment by dipshit** [comment]
thanks for the tip @bkzhang , I missed that as I didn't get to review it a second time
