### ISSUE TITLE
Weekly Scrum - [3/27/2020]

### ISSUE THREAD

**Issue by JackyChiu** [vikrambombhi/SimpleSurvey#82]
This week I worked on:
- Adding the question controller with the functionality of answering #75, #81 
- Adding circuit breakers into our endpoints #80 
- Worked on presentation slides for #77

**Comment by dipshit** [comment]
This week I worked on:
 * Fighting depression
 * #71 for making new survey form fixed & working
 * Reviewing a lot of PRs

**Comment by bkzhang** [comment]
This week I worked on:

- Reviewing PRs
- Working on the Hystrix presentation #77

**Comment by ismail-syed** [comment]
* Added react test to CI https://github.com/vikrambombhi/SimpleSurvey/pull/59

**Comment by vikrambombhi** [comment]
This week:
- Reviewed PRs
- Hystrix presentation slides

**Comment by bkzhang** [comment]
Should keep this visible until after milestone 3 deadline
