### ISSUE TITLE
Weekly Scrum - [4/3/2020]

### ISSUE THREAD

**Issue by JackyChiu** [vikrambombhi/SimpleSurvey#83]
Last week I worked on: ref to #82 

This week I worked on:
- Presentation Slides
- Responding to code review feedback
- Recording presentation
- Field validation for answering questions #98 
- Reviewing PRs
- Charting histogram #99

**Comment by dipshit** [comment]
This week I worked on:

* Cardio
* New Survey functionality #46 #76 #79 

Next week I will work on:

* demo for presentation #77 
* counter-strike gaming
* practicing presentation

**Comment by ismail-syed** [comment]
This week I will work on: 
* Ability to delete a survey and update UI
* Ability to re-open a survey
* Enable the admin to view survey answers

**Comment by vikrambombhi** [comment]
This week I did:
- Added page to review answers
- (review answers page) Pie chart for choice answers
- (review answers page) List text answers
- Fixed small performance bug where all surveys were being fetched when editing a single one

**Comment by dipshit** [comment]
This week I worked on displaying answers on the front end & reviewing other people's PRs. No blockers for me right now.

**Comment by bkzhang** [comment]
This week I worked on:

- Fixing bugs like removing the ability to complete a survey if its closed #89 and reloading the page when a survey is closed #70 
- Redid the add button UI and moved it to into the create a survey card #104 so that its more noticeable
