### ISSUE TITLE
Make the add Questions UI more visible

### ISSUE THREAD

**Issue by ismail-syed** [vikrambombhi/SimpleSurvey#88]
> Currently after I create a survey, the survey is always empty when I try to fill it.

Feedback from TA

<img width="992" alt="Screen Shot 2020-03-30 at 11 08 40 PM" src="https://user-images.githubusercontent.com/6130700/77982902-75eb9880-72db-11ea-80c7-132fe364cf36.png">

**Comment by bkzhang** [comment]
it should be below Name and above the submit button imo
